DROP SCHEMA IF EXISTS StartwellDB;
CREATE SCHEMA StartwellDB;
USE StartwellDB;

CREATE TABLE UserBuckets (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    BucketType VARCHAR (45) NOT NULL UNIQUE,
    BucketDesc VARCHAR(45),
    PRIMARY KEY (SNo)
);

CREATE TABLE Users (
  UserID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  EmailID VARCHAR(45) NOT NULL UNIQUE,
  UserType Enum('Admin','Provider','Customer'),
  Pass VARCHAR (45) NOT NULL,
  First_Name VARCHAR(45) NOT NULL,
  Last_Name VARCHAR(45) NOT NULL,
  DOB DATE  NULL,
  Sex VARCHAR(20),
  LicenseID VARCHAR(25) UNIQUE,
  BucketType VARCHAR(10),
  Current_Status VARCHAR(20),
  Subscription VARCHAR(20),
  last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  resetPasswordToken varchar(150),
  resetPasswordTokenExpires varchar(150),
  PRIMARY KEY  (UserID),
  FOREIGN KEY (BucketType) REFERENCES UserBuckets(BucketType)
);

CREATE TABLE SCategories (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CategoryID VARCHAR(10) NOT NULL UNIQUE,
    BucketType VARCHAR(20) NOT NULL,
    CatDesc VARCHAR(45),
    PRIMARY KEY (SNo),
    FOREIGN KEY (BucketType) REFERENCES UserBuckets (BucketType)
);

CREATE TABLE Surveys (
	SurveyID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    SurveyTitle VARCHAR(30) NOT NULL,
    NoQues INT UNSIGNED NOT NULL,
    OptDesc VARCHAR(30) NOT NULL,
    CategoryID VARCHAR(45) NOT NULL,
    SurveyStatus CHAR(1) NOT NULL,
    PRIMARY KEY(SurveyID),
    FOREIGN KEY (CategoryID) REFERENCES SCategories (CategoryID)
);

CREATE TABLE UserSurveyHeader (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    EmailID VARCHAR (45) NOT NULL,
    SurveyID INT UNSIGNED NOT NULL,
    AttemptID INT UNSIGNED NOT NULL,
    SurveyStatus CHAR(1) NOT NULL,
    Time_stamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SNo),
    FOREIGN KEY (SurveyID) REFERENCES Surveys (SurveyID),
    FOREIGN KEY (EmailID) REFERENCES Users (EmailID),
    UNIQUE KEY Attempts (EmailID, SurveyID, AttemptID)
);

CREATE TABLE SQuestions (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    SurveyID INT UNSIGNED NOT NULL,
    QuesID INT UNSIGNED NOT NULL,
    QText VARCHAR(90) NOT NULL,
    RespType CHAR(10) NOT NULL,
    PRIMARY KEY (SNo),
    FOREIGN KEY (SurveyID) REFERENCES Surveys (SurveyID)
);

CREATE TABLE QOptions (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    SurveyID INT UNSIGNED NOT NULL,
	Combination INT UNSIGNED NOT NULL,
    OptID INT UNSIGNED NOT NULL,
    OptText VARCHAR (45) NOT NULL,
    PRIMARY KEY (SNo),
    FOREIGN KEY (SurveyID) REFERENCES Surveys (SurveyID),
    FOREIGN KEY (Combination) REFERENCES SQuestions (SNo)
);

CREATE TABLE UserResponses (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    EmailID VARCHAR(45) NOT NULL,
    UserType Enum('Admin','Provider','Customer'), NOT NULL,
    SurveyID INT UNSIGNED NOT NULL,
    AttemptID INT UNSIGNED NOT NULL,
    Combination INT UNSIGNED NOT NULL,
    Response VARCHAR(45),
    Time_stamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SNo),
    FOREIGN KEY (EmailID) REFERENCES Users (EmailID),
    FOREIGN KEY (SurveyID) REFERENCES Surveys (SurveyID),
    FOREIGN KEY (Combination) REFERENCES SQuestions (SNo)
);

CREATE TABLE RelTypes (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    RelType VARCHAR(45) NOT NULL UNIQUE,
    RelDesc VARCHAR(90),
    PRIMARY KEY (SNo)
);

CREATE TABLE newsletter (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(45) NOT NULL UNIQUE,
    PRIMARY KEY (SNo)
);

CREATE TABLE contactUs (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(45) NOT NULL,
    subject VARCHAR(45) NOT NULL,
    message VARCHAR(200),
    PRIMARY KEY (SNo)
);

CREATE TABLE UserRelationships (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    EmailID VARCHAR (45) NOT NULL,
    RelType VARCHAR(45) NOT NULL,
    LinkedUserID VARCHAR (20) NOT NULL,
    PRIMARY KEY (SNo),
    FOREIGN KEY (EmailID) REFERENCES Users(EmailID),
    FOREIGN KEY (LinkedUserID) REFERENCES Users(EmailID),
    FOREIGN KEY (RelType) REFERENCES RelTypes(RelType)
);

CREATE TABLE WebsiteContent (
	SNo INT UNSIGNED NOT NULL AUTO_INCREMENT,
    BucketType VARCHAR(45) NOT NULL,
    ContentType CHAR(1) NOT NULL,
    LocationID VARCHAR(45) NOT NULL,
    URL VARCHAR (90) NOT NULL,
    PRIMARY KEY (SNo),
    FOREIGN KEY (BucketType) REFERENCES UserBuckets(BucketType)
);